mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult AdminLogin()
        {
            return View();
        }
        
    }
}

mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mvc/Controllers/loginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class loginController : Controller
    {
        // GET: login
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
    }
}

mvc/Views/Admin/AdminLogin.cshtml
@*@{
    ViewBag.Title = "AdminLogin";
    Layout = "~/Views/LayoutPage1.cshtml";
}*@


</head>

   <body style="
    background-image: url(https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2); background-size: 100vw 100vh;
">
    <div style="margin: 40px auto; color: white;">
        <section style="max-width: 650px; padding: 30px 20px; background: rgba(0,0,0, 0.7); border-radius: 10px">
            <div class="container-fluid h-custom">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-md-9 col-lg-6 col-xl-5" style="margin-top: 30px">
                        <img width="320" src="~/Images/foodDelivery.png"
                             class="img-fluid" alt="Sample image">
                    </div>
                    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                        <form>
                            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                                <p class="lead fw-normal mb-0 me-3">Hey Admin! Welcome!</p>

                            </div>



                            <!-- Email input -->
                            <div class="form-outline mb-4" style="margin-top: 15px">

                                <label class="form-label" for="form3Example4">Email</label>
                                <input type="email" id="form3Example3" class="form-control form-control-lg"
                                       placeholder="Enter a valid email address" />

                            </div>

                            <!-- Password input -->
                            <div class="form-outline mb-3" style="margin-top: 15px">
                                <label class="form-label" for="form3Example4">Password</label>
                                <input type="password" id="form3Example4" class="form-control form-control-lg"
                                       placeholder="Enter password" />
                            </div>

                            <div class="d-flex justify-content-between align-items-center">
                                <!-- Checkbox -->
                                <div class="form-check mb-0">
                                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                                    <label class="form-check-label" for="form2Example3">
                                        Remember me
                                    </label>
                                </div>
                                <a href="#!" class="text-body">Forgot password?</a>
                            </div>

                            <div class="text-lg-start mt-4 pt-2" style="margin-top: 15px">
                                <button type="button" class="btn btn-primary btn-lg"
                                        style="padding-left: 2.5rem; padding-right: 2.5rem;">
                                    Login
                                </button>
                                
                                                    </div>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </body>
                      

mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    <link href="~/style/homestyle.css" rel="stylesheet" />
}

<body style=" background-image: url(https://images.pexels.com/photos/1603899/pexels-photo-1603899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2); background-size: 100vw 100vh; ">
    <div class="header">
        <h1 style="color:whitesmoke;font-weight:bold;font-size:100px;font-style:italic;animation-name:revert;animation-duration:10s">Food Creww!</h1>
        <p style="color:yellow;font-weight:bold;font-size:40px">Satisfy your cravings with our delivery!</p>
    </div>
   
</body>

mvc/Views/LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="~/style/style.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EzyDelivery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin", "AdminLogin", "Admin")</li>
                    <li>@Html.ActionLink("Login", "Login", "login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

mvc/Views/login/Login.cshtml
@*@{
    ViewBag.Title = "Login";
    Layout = "~/Views/LayoutPage1.cshtml";
}

<h2>Login</h2>*@


</head>
<body style=" background-image: url(https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1); background-size: 100vw 100vh; ">
    <div style="margin: 40px auto; color: white;">
        <section style="max-width: 650px; padding: 30px 20px; background: rgba(0,0,0, 0.7); border-radius: 10px">
            <div class="container-fluid h-custom">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-md-9 col-lg-6 col-xl-5" style="margin-top: 30px">
                        <img width="320" src="~/Images/foodDelivery.png"
                             class="img-fluid" alt="Sample image">
                    </div>
                    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                        <form>
                            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                                <p class="lead fw-normal mb-0 me-3">If you are a new user</p>
                                <p class="lead fw-normal mb-0 me-3">Signin here!</p>
                            </div>

                  

                            <!-- Email input -->
                            <div class="form-outline mb-4" style="margin-top: 15px">
                               
                                <label class="form-label" for="form3Example4">Email</label>
                                <input type="email" id="form3Example3" class="form-control form-control-lg"
                                       placeholder="Enter a valid email address" />
                                
                            </div>

                            <!-- Password input -->
                            <div class="form-outline mb-3" style="margin-top: 15px">
                                <label class="form-label" for="form3Example4">Password</label>
                                <input type="password" id="form3Example4" class="form-control form-control-lg"
                                       placeholder="Enter password" />
                            </div>

                            <div class="d-flex justify-content-between align-items-center">
                                <!-- Checkbox -->
                                <div class="form-check mb-0">
                                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                                    <label class="form-check-label" for="form2Example3">
                                        Remember me
                                    </label>
                                </div>
                                <a href="#!" class="text-body">Forgot password?</a>
                            </div>

                            <div class="text-lg-start mt-4 pt-2" style="margin-top: 15px">
                                <button type="button" class="btn btn-primary btn-lg"
                                        style="padding-left: 2.5rem; padding-right: 2.5rem;">
                                    Login
                                </button>
                                <p class="small fw-bold mt-2 pt-1 mb-0">
                                    Don't have an account? <a href="#!"
   class="link-danger">@Html.ActionLink("Register Now", "Register", "login")</a>
                                </p>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

mvc/Views/login/Register.cshtml
<body style=" 
    background-image: url(https://images.pexels.com/photos/616401/pexels-photo-616401.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
    background-size: 100vw 100vh;
">
    <div style="margin: 40px auto; color: white;">
        <section style="max-width: 650px;padding: 30px 20px; background: rgba(0,0,0, 0.7); border-radius: 10px">
            <div class="container-fluid h-custom">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-md-9 col-lg-6 col-xl-5" style="margin-top: 30px">
                        <img width="320" src="~/Images/foodDelivery.png"
                             class="img-fluid" alt="Sample image">
                    </div>
                    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                        <form>


                            <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                                <p class="lead fw-normal mb-0 me-3">Register Now </p>
                            </div>

                            <div class="form-outline mb-4" style="margin-top: 15px">

                                <label class="form-label" for="form3Example4">Full Name</label>
                                <input type="text" id="form3Example3" class="form-control form-control-lg"
                                       placeholder="Enter your full name" />

                            </div>

                            <div class="form-outline mb-4" style="margin-top: 15px">

                                <label class="form-label" for="form3Example4">Mobile</label>
                                <input type="number" id="form3Example3" class="form-control form-control-lg"
                                       placeholder="Enter a valid Mobile Number" />

                            </div>


                            <!-- Email input -->
                            <div class="form-outline mb-4" style="margin-top: 15px">

                                <label class="form-label" for="form3Example4">Email</label>
                                <input type="email" id="form3Example3" class="form-control form-control-lg"
                                       placeholder="Enter a valid email address" />

                            </div>

                            <!-- Password input -->
                            <div class="form-outline mb-3" style="margin-top: 15px">
                                <label class="form-label" for="form3Example4">Password</label>
                                <input type="password" id="form3Example4" class="form-control form-control-lg"
                                       placeholder="Enter password" />
                            </div>
                            <div class="form-outline mb-3" style="margin-top: 15px">
                                <label class="form-label" for="form3Example4">Confirm Password</label>
                                <input type="password" id="form3Example4" class="form-control form-control-lg"
                                       placeholder="Enter password" />
                            </div>

                            <!--<div class="d-flex justify-content-between align-items-center">-->
                                <!-- Checkbox -->
                                <!--<div class="form-check mb-0">
                                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                                    <label class="form-check-label" for="form2Example3">
                                        Remember me
                                    </label>
                                </div>
             
                            </div>-->

                            <div class="text-lg-start mt-4 pt-2" style="margin-top: 15px">
                                <button type="button" class="btn btn-primary btn-lg"
                                        style="padding-left: 2.5rem; padding-right: 2.5rem;">
                                    Register
                                </button>
                                <p class="small fw-bold mt-2 pt-1 mb-0">
                                    Have an account? <a href="#!"
   class="link-danger">@Html.ActionLink("Login", "Login", "login")</a>
                                </p>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>